"""gp_sonar_report — build full Sonar session reports (T-0037).

The existing GUI export dumps only self.aps. A real customer evidence package
needs the full picture: AP list + Karma rigs + IE fingerprint baseline + which
attack-toolkit signature DB version was active + when the session ran. This
module builds that bundle in two formats:

    build_json_report(...)  → machine-readable dict
    build_html_report(...)  → standalone HTML, embeddable in email/PDF

Inputs are passed in by the caller (gp-sonar.py); the module deliberately
imports nothing GTK-specific so the same builder can be reused by future
headless/CLI exporters.
"""
import datetime as _dt
import hashlib
import html

REPORT_SCHEMA_VERSION = "1.0"

_HTML_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Sonar Session Report — {generated_at}</title>
<style>
 body {{ background:#0a0a0a; color:#e6e6e6; font-family:'JetBrains Mono','Menlo',monospace;
        margin:0; padding:32px; line-height:1.5; }}
 h1 {{ color:#39ff8f; border-bottom:2px solid #39ff8f; padding-bottom:8px; margin-top:0; }}
 h2 {{ color:#39ff8f; margin-top:32px; border-bottom:1px solid #2a2a2a; padding-bottom:4px; }}
 .meta {{ color:#888; font-size:0.9em; }}
 table {{ border-collapse:collapse; width:100%; margin-top:8px; font-size:0.9em; }}
 th, td {{ border:1px solid #2a2a2a; padding:6px 10px; text-align:left; vertical-align:top; }}
 th {{ background:#161616; color:#39ff8f; }}
 .threat-dangerous {{ color:#ff5050; font-weight:bold; }}
 .threat-suspicious {{ color:#ffaa33; }}
 .threat-warning {{ color:#ffd450; }}
 .threat-safe {{ color:#39ff8f; }}
 .empty {{ color:#666; font-style:italic; }}
 code {{ background:#161616; padding:1px 4px; border-radius:2px; }}
 .footer {{ margin-top:48px; color:#555; font-size:0.85em; border-top:1px solid #2a2a2a;
            padding-top:12px; }}
</style>
</head>
<body>
<h1>Sonar Session Report</h1>
<p class="meta">Generated {generated_at} UTC · Sonar {sonar_version} · Schema {schema_version}</p>

<h2>Session</h2>
<table>
<tr><th>Last scan</th><td>{last_scan_time}</td></tr>
<tr><th>Our AP SSID</th><td>{our_ssid}</td></tr>
<tr><th>Our AP BSSID</th><td><code>{our_bssid}</code></td></tr>
<tr><th>IE fingerprint baseline</th><td><code>{our_fingerprint}</code></td></tr>
<tr><th>Trusted APs</th><td>{trusted_count}</td></tr>
<tr><th>Signatures loaded</th><td>{sig_count} ({sig_db_hash})</td></tr>
</table>

<h2>Access Points Observed ({ap_count})</h2>
{ap_table}

<h2>Karma Rigs Detected ({karma_count})</h2>
{karma_table}

<h2>Cross-Session Karma History ({history_count})</h2>
{history_table}

<h2>Trusted AP List ({trusted_count_2})</h2>
{trusted_table}

<div class="footer">
This report was generated by Phantom OS Sonar. Each Karma rig entry was identified by
either probe-response identity mismatch or response-to-decoy SSIDs — see the rig's
"reason" field for the specific signal that triggered the flag.
</div>
</body>
</html>
"""


def _now_iso():
    return _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _sig_db_hash(signatures):
    """Stable identifier for the loaded signature DB so an evidence consumer can
    confirm 'this report was generated against the version with these IDs.'
    """
    if not signatures:
        return "(none loaded)"
    ids = sorted((s.get("id", "") for s in signatures))
    return hashlib.sha256("|".join(ids).encode()).hexdigest()[:12]


def _our_fingerprint(our_bssid, trusted):
    bssid = (our_bssid or "").lower()
    for t in trusted or []:
        if (t.get("bssid", "") or "").lower() == bssid:
            return t.get("fingerprint") or "(no baseline)"
    return "(no baseline)"


def build_json_report(*, aps, karma_rigs, our_ssid, our_bssid, trusted,
                      signatures, last_scan_time, sonar_version="unknown",
                      encounter_history=None):
    """Return a dict suitable for json.dump."""
    return {
        "schema_version": REPORT_SCHEMA_VERSION,
        "sonar_version": sonar_version,
        "generated_at": _now_iso(),
        "session": {
            "last_scan_time": last_scan_time or "(no scan run)",
            "our_ssid": our_ssid or "",
            "our_bssid": our_bssid or "",
            "our_fingerprint": _our_fingerprint(our_bssid, trusted),
            "trusted_count": len(trusted or []),
            "signature_count": len(signatures or []),
            "signature_db_hash": _sig_db_hash(signatures or []),
        },
        "aps": list(aps or []),
        "karma_rigs": [
            {"bssid": k, **(v if isinstance(v, dict) else {"value": v})}
            for k, v in (karma_rigs or {}).items()
        ],
        "trusted_aps": list(trusted or []),
        "encounter_history": list(encounter_history or []),
    }


def _ap_row(ap):
    threat = (ap.get("threat") or "safe").lower()
    label = ap.get("threat_label") or threat.upper()
    sig = ap.get("signal")
    sig_str = f"{sig} dBm" if isinstance(sig, int) else "?"
    return (
        f'<tr><td><code>{html.escape(ap.get("bssid","?"))}</code></td>'
        f'<td>{html.escape(ap.get("ssid",""))}</td>'
        f'<td>{html.escape(sig_str)}</td>'
        f'<td>{html.escape(ap.get("encryption","?"))}</td>'
        f'<td class="threat-{html.escape(threat)}">{html.escape(label)}</td>'
        f'<td><code>{html.escape((ap.get("ie_fingerprint") or "")[:32])}</code></td></tr>'
    )


def _karma_row(bssid, info):
    info = info or {}
    sig = info.get("signal")
    sig_str = f"{sig} dBm" if isinstance(sig, int) else "?"
    return (
        f'<tr><td><code>{html.escape(bssid)}</code></td>'
        f'<td>{html.escape(info.get("decoy_ssid",""))}</td>'
        f'<td>{html.escape(info.get("real_ssid",""))}</td>'
        f'<td>{html.escape(sig_str)}</td>'
        f'<td>{html.escape(info.get("first_seen",""))}</td>'
        f'<td>{html.escape(info.get("reason",""))}</td></tr>'
    )


def _history_row(rec):
    rec = rec or {}
    ctx = rec.get("context") or {}
    sig = rec.get("signal_dbm")
    sig_str = f"{sig} dBm" if isinstance(sig, int) else "?"
    return (
        f'<tr><td>{html.escape(rec.get("ts",""))}</td>'
        f'<td><code>{html.escape(rec.get("bssid",""))}</code></td>'
        f'<td>{html.escape(rec.get("decoy_ssid",""))}</td>'
        f'<td>{html.escape(rec.get("real_ssid",""))}</td>'
        f'<td>{html.escape(sig_str)}</td>'
        f'<td>{html.escape(ctx.get("our_ssid",""))}</td></tr>'
    )


def _trusted_row(t):
    t = t or {}
    return (
        f'<tr><td><code>{html.escape(t.get("bssid",""))}</code></td>'
        f'<td>{html.escape(t.get("ssid",""))}</td>'
        f'<td><code>{html.escape((t.get("fingerprint","") or "")[:32])}</code></td>'
        f'<td>{html.escape(t.get("added",""))}</td></tr>'
    )


def _table(headers, rows, empty_msg):
    if not rows:
        return f'<p class="empty">{html.escape(empty_msg)}</p>'
    th = "".join(f"<th>{html.escape(h)}</th>" for h in headers)
    return f'<table><thead><tr>{th}</tr></thead><tbody>{"".join(rows)}</tbody></table>'


def build_html_report(*, aps, karma_rigs, our_ssid, our_bssid, trusted,
                      signatures, last_scan_time, sonar_version="unknown",
                      encounter_history=None):
    """Return a self-contained HTML string."""
    aps = aps or []
    karma_rigs = karma_rigs or {}
    trusted = trusted or []
    encounter_history = encounter_history or []
    signatures = signatures or []

    return _HTML_TEMPLATE.format(
        generated_at=_now_iso(),
        sonar_version=html.escape(sonar_version),
        schema_version=REPORT_SCHEMA_VERSION,
        last_scan_time=html.escape(last_scan_time or "(no scan run)"),
        our_ssid=html.escape(our_ssid or ""),
        our_bssid=html.escape(our_bssid or ""),
        our_fingerprint=html.escape(_our_fingerprint(our_bssid, trusted)),
        trusted_count=len(trusted),
        trusted_count_2=len(trusted),
        sig_count=len(signatures),
        sig_db_hash=_sig_db_hash(signatures),
        ap_count=len(aps),
        karma_count=len(karma_rigs),
        history_count=len(encounter_history),
        ap_table=_table(
            ["BSSID", "SSID", "Signal", "Encryption", "Threat", "IE Fingerprint"],
            [_ap_row(a) for a in aps],
            "No scan results recorded in this session.",
        ),
        karma_table=_table(
            ["BSSID", "Decoy SSID", "Real SSID", "Signal", "First Seen", "Reason"],
            [_karma_row(b, v) for b, v in karma_rigs.items()],
            "No Karma rigs detected this session.",
        ),
        history_table=_table(
            ["Timestamp (UTC)", "BSSID", "Decoy", "Real", "Signal", "Near"],
            [_history_row(r) for r in encounter_history],
            "No cross-session Karma history (or history not requested).",
        ),
        trusted_table=_table(
            ["BSSID", "SSID", "Fingerprint", "Added"],
            [_trusted_row(t) for t in trusted],
            "No trusted APs configured.",
        ),
    )
